apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: old-iam-users-app
    env: production
  name: old-iam-users-app
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      labels:
        env: production
        app: old-iam-users-app
    spec:
      containers:
        - name: old-iam-users-app
          image: how0326/musinsa
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: secret-configs
            - configMapRef:
                name: configs
          livenessProbe:
            httpGet:
              path: /api/health-check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health-check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
